music:
  nbs_directory: /home/tim/minecraft/mcparty/var/nbs
  exclude: [ ]
database:
  username: plugin_user
  password: no_pw_needed
  hostname: localhost
  port: 27017
default_world:
  name: world
  origin:
    x: 0
    y: 65
    z: 0
kit_database_path: /home/tim/minecraft/mcparty/var/kits