name: MinecraftParty
version: '${project.version}'
main: me.timwastaken.minecraftparty.MinecraftParty
api-version: 1.18
authors: [ TimWasTaken ]
description: Minecraft Party gamemode (mix of cytooxien mario party and itsjerryandharry herobrines chamber)
depend: [ NoteBlockAPI ]
commands:
  minigame:
    description: Loads the specified minigame
    usage: minigame <load|stop> <minigame_type>
    aliases:
      - loadgame
      - game
      - load
      - mg
  music:
    description: Lets players play music
    usage: music <play|stop|toggle> <nbs_file_name>
  inventory:
    description: utility for arranging inventory layouts
    aliases:
      - inv
      - layout
